"""create_user_device_claimcode_table

Revision ID: 50816f38403b
Revises:
Create Date: 2026-06-16 18:10:19.135443

"""

from typing import Sequence, Union
import uuid
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa
import sqlmodel

from app.utils.password import get_hashed_password


# revision identifiers, used by Alembic.
revision: str = "50816f38403b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    now = datetime.now(timezone.utc)
    admin_user_id = str(uuid.uuid4())
    test_user_id = str(uuid.uuid4())
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "firstname", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "lastname", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    user_table = sa.table(
        "user",
        sa.column("id", sa.String()),
        sa.column("username", sa.String()),
        sa.column("email", sa.String()),
        sa.column("password", sa.String()),
        sa.column("is_admin", sa.Boolean()),
        sa.column("is_active", sa.Boolean()),
        sa.column("firstname", sa.String()),
        sa.column("lastname", sa.String()),
        sa.column("phone", sa.String()),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        user_table,
        [
            {
                "id": admin_user_id,
                "username": "admin",
                "email": "admin@example.com",
                "password": get_hashed_password(b"1234").decode(),
                "is_admin": True,
                "is_active": True,
                "firstname": None,
                "lastname": None,
                "phone": None,
                "created_at": now,
            },
            {
                "id": test_user_id,
                "username": "test",
                "email": "test@example.com",
                "password": get_hashed_password(b"1234").decode(),
                "is_admin": False,
                "is_active": True,
                "firstname": None,
                "lastname": None,
                "phone": None,
                "created_at": now,
            },
        ],
    )
    op.create_table(
        "device",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "api_key", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_device_code"), "device", ["code"], unique=True)
    device_table = sa.table(
        "device",
        sa.column("id", sa.String()),
        sa.column("code", sa.String()),
        sa.column("api_key", sa.String()),
        sa.column("is_active", sa.Boolean()),
        sa.column("owner_id", sa.String()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        device_table,
        [
            {
                "id": str(uuid.uuid4()),
                "code": "test-device",
                "api_key": "test-device-api-key",
                "is_active": True,
                "owner_id": test_user_id,
                "created_at": now,
                "updated_at": now,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if inspector.has_table("claimcode"):
        indexes = inspector.get_indexes("claimcode")
        if any(idx["name"] == "ix_claimcode_code" for idx in indexes):
            op.drop_index("ix_claimcode_code", table_name="claimcode")
        op.drop_table("claimcode")
    op.drop_index(op.f("ix_device_code"), table_name="device")
    op.drop_table("device")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
