"""create_recording_tables

Revision ID: 7a3b2c1d8e9f
Revises: 50816f38403b
Create Date: 2026-06-28 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "7a3b2c1d8e9f"
down_revision: Union[str, Sequence[str], None] = "50816f38403b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.create_table(
        "recording",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "filename", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("device_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "data_run_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.ForeignKeyConstraint(["device_id"], ["device.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recording_data_run_id"), "recording", ["data_run_id"], unique=True
    )
    op.create_table(
        "recordingsample",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recording_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.Column("accel_z", sa.Float(), nullable=False),
        sa.Column("speed", sa.Float(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("roughness_score", sa.Float(), nullable=False),
        sa.Column("severity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["recording_id"], ["recording.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_recordingsample_recording_id",
        "recordingsample",
        ["recording_id"],
        postgresql_using="btree",
    )
    op.create_index(
        "ix_recordingsample_recorded_at",
        "recordingsample",
        ["recorded_at"],
        postgresql_using="btree",
    )
    op.create_index(
        "ix_recordingsample_geom", "recordingsample", ["geom"], postgresql_using="gist"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_recordingsample_geom", table_name="recordingsample")
    op.drop_index("ix_recordingsample_recorded_at", table_name="recordingsample")
    op.drop_index("ix_recordingsample_recording_id", table_name="recordingsample")
    op.drop_table("recordingsample")
    op.drop_index(op.f("ix_recording_data_run_id"), table_name="recording")
    op.drop_table("recording")
    # ### end Alembic commands ###
